### ISSUE TITLE
Support for `SpecRestApi` (Unsupported Resource Type `AWS::ApiGateway::RestApi`)

### ISSUE THREAD

**Issue by smcroskey** [hashicorp/cdktf-aws-cdk#84]
*Context: We have been looking to use the AWS Adapter to leverage the power of the AWS CDK while maintaining compatibility with our internal tooling that is built around TF.*

We want to leverage the [`SpecRestApi`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigateway.SpecRestApi.html) AWS construct to simplify how we provision and deploy REST APIs, using OpenAPI to define them.  However, it looks like this isn't supported currently by the AWS Adapter: 

```ts
        const apiDefinition = YAML.parse(readFileSync(path.join(__dirname, './openapi.yaml'), {encoding: 'utf-8'}))
        const api = new SpecRestApi(this.awsAdapter, 'My Service API', {
            restApiName: 'My Service API',
            apiDefinition: ApiDefinition.fromInline(apiDefinition),
        })
        api.root.addProxy({
            anyMethod: true,
            defaultIntegration: new LambdaIntegration(proxyLambda, {proxy: true, allowTestInvoke: true})
        })
```

Error:
```
Unsupported resource Type AWS::ApiGateway::RestApi. There is no custom mapping registered for AWS::ApiGateway::RestApi and the AWS CloudControl API does not seem to support it yet.
```

I started going down the rabbit hole of introducing the manual mapping following the instructions in the README (adding a `AWS::ApiGateway::RestApi` and `AWS::ApiGateway::Deployment`), but eventually had to give up when `ckdtf synth` failed with something about not being able to resolve a `AWS::URLSuffix`.

I think the RestApi and SpecRestApi constructs are quite powerful in removing a lot of boilerplate that we need to deal with when using straight TF resources (either in HCL or cdktf)...can we add support for these mappings in the AWS Adapter?

**Comment by skorfmann** [comment]
> That said, the `AWS::URLSuffix` intrinsic value is something we should add support for too then (I can help with that!). It'll probably be quite similar to the `AWS::Partition`:

Just came across this as well 👍
