### ISSUE TITLE
Error when 'grantReadWriteData' on a DDB table to an IGrantable Construct

### ISSUE THREAD

**Issue by ryancormack** [hashicorp/cdktf-aws-cdk#97]
Repo with reproduction: https://github.com/ryancormack/cdktf-ddb-bug

### Description

Using a DDB table's `grantReadWriteData` method to create the permission set to allow a Lambda function to read and write the data results in an error.
`grantReadData`
`grantWriteData`
`grantFullAccess`
All exhibit the same behaviour

#### Expected result

A Terraform json document with a lambda policy that permits access to the DDB table.

#### Actual

```
⠧  Synthesizing
[2022-09-09T17:18:28.723] [ERROR] default - /Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:358
        throw new Error(`unable to resolve pseudo reference ${ref}`);
              ^

[2022-09-09T17:18:28.725] [ERROR] default - Error: unable to resolve pseudo reference AWS::NoValue
    at TerraformHost.resolvePseudo (/Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:358:15)
    at TerraformHost.resolveRef (/Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:364:19)
    at TerraformHost.processIntrinsics (/Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:293:19)
    at /Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:288:34
    at Array.map (<anonymous>)
    at TerraformHost.processIntrinsics (/Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:288:18)
    at TerraformHost.processIntrinsics (/Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:307:24)
    at /Users/ryan.cormack/code/ryancormack/cdktf-ddb-bug/node_modules/@cdktf/aws-cdk/src/aws-adapter.ts:288:34
    at Array.map (<anonymous>)
ERROR: cdktf encountered an error while synthesizing

Synth command: npx ts-node main.ts
Error:         non-zero exit code 1
```

#### Environment

```
% cdktf --version
0.12.2
% terraform --version
Terraform v1.2.1
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.2.9. You can update by downloading from https://www.terraform.io/downloads.html
% node --version
v16.15.0
```

**Comment by ryancormack** [comment]
This can be worked around by creating a Policy construct:
```
    const writeToDynamoPolicy = new PolicyStatement({
      actions: ["ddb:*"],
      resources: [table.tableArn],
    });

    lambda.role?.attachInlinePolicy(
      new Policy(awsAdapter, "policy", {
        statements: [writeToDynamoPolicy],
      })
    );
```

**Comment by ryancormack** [comment]
I know the DDB Cloud Control API support is new in the repo. I wanted to highlight this as not quite working in it. I'm not sure where to even start looking to try and find the bug though I'm afraid.

**Comment by ansgarm** [comment]
Hi @ryancormack 👋

It does not seem to be a bug that you could solve but rather a missing implementation for the `AWS::NoValue` which would need to be added to this switch-statement here: https://github.com/hashicorp/cdktf-aws-cdk/blob/6310f43a19b2e413fe5f2aaa0ece4a90628cfb96/src/aws-adapter.ts#L336

I'm unsure whether returning `undefined` might already do the trick but it might be worth a try. The easiest way (as you already have a reproduction example) to confirm this, could be to go into the `node_modules` into the JS code of the AWS Adapter and adjust that part to handle this value.

Alternatively you could help me by posting a small example that I can use to test this.

**Comment by ryancormack** [comment]
Thanks for the direction. I was looking around there, but struggling to see how everything joins together. I need to read through the project a bit more (I'm really interested in how it develops).

I've went with your guidance and it seems to work as expected. This is the ouput I get for the generated IAM policy:

```
"aws_iam_policy": {
      "adapter_DemoLambdaServiceRoleDefaultPolicy7078F2E7_4DFECAA0": {
        "//": {
          "metadata": {
            "path": "cdktf-ddb-bug/adapter/DemoLambdaServiceRoleDefaultPolicy7078F2E7",
            "uniqueId": "adapter_DemoLambdaServiceRoleDefaultPolicy7078F2E7_4DFECAA0"
          }
        },
        "policy": "${jsonencode({Statement = [{Action = [\"dynamodb:BatchGetItem\", \"dynamodb:GetRecords\", \"dynamodb:GetShardIterator\", \"dynamodb:Query\", \"dynamodb:GetItem\", \"dynamodb:Scan\", \"dynamodb:ConditionCheckItem\", \"dynamodb:BatchWriteItem\", \"dynamodb:PutItem\", \"dynamodb:UpdateItem\", \"dynamodb:DeleteItem\", \"dynamodb:DescribeTable\"], Effect = \"Allow\", Resource = [jsondecode(aws_cloudcontrolapi_resource.adapter_DemoTableEE720AED_204A7B6B.properties)[\"Arn\"]]}], Version = \"2012-10-17\"})}"
      }
    },
```

I'm just setting up an account I can deploy it to to verify there.

**Comment by ansgarm** [comment]
Wow, great! Thanks @ryancormack 👍
